# Generated by Django 5.2 on 2025-04-06 08:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0002_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ident', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Scheduled', 'Scheduled'), ('Finished', 'Finished')], default='New', max_length=10)),
                ('schedule_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('schedule_table', models.IntegerField(default=0)),
                ('result_robot1_points', models.IntegerField(default=0)),
                ('result_robot2_points', models.IntegerField(default=0)),
                ('robot1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot1_matches', to='smtracker.robot')),
                ('robot2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot2_matches', to='smtracker.robot')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='smtracker.round')),
            ],
        ),
    ]
