# Generated by Django 5.2 on 2025-04-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0003_alter_robot_id_alter_round_id_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
    ]
