# Generated by Django 5.2 on 2025-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0004_alter_match_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_type',
            field=models.CharField(choices=[('None', 'None'), ('Round-Robin', 'Round-Robin'), ('Knockout', 'Knockout'), ('Swiss', 'Swiss')], default='None', max_length=20),
        ),
    ]
