# Generated by Django 5.2 on 2025-04-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0005_round_round_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='country',
            field=models.CharField(max_length=10),
        ),
    ]
