# Generated by Django 5.2 on 2025-04-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0006_alter_robot_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='byebot_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='robot_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='round_group1_qualified',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='round_group2_qualified',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='round_group3_qualified',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='round_group_index',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_robot_points', models.IntegerField(default=0)),
                ('round_group1_points', models.IntegerField(blank=True, null=True)),
                ('round_group2_points', models.IntegerField(blank=True, null=True)),
                ('round_group3_points', models.IntegerField(blank=True, null=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='smtracker.robot')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='smtracker.round')),
            ],
        ),
    ]
