# Generated by Django 5.2 on 2025-04-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0007_robot_byebot_points_robot_robot_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='is_byebot',
            field=models.IntegerField(default=0),
        ),
    ]
