# Generated by Django 5.2 on 2025-04-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0008_robot_is_byebot'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundresult',
            name='total_robot_points',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='total_robot_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
