# Generated by Django 5.2 on 2025-04-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0009_roundresult_total_robot_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundresult',
            name='total_opponent_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
