# Generated by Django 5.2 on 2025-04-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0010_roundresult_total_opponent_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='round_group1_qualified',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
