# Generated by Django 5.2 on 2025-04-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0011_alter_robot_round_group1_qualified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='is_byebot',
            field=models.IntegerField(default=0, verbose_name='bye'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='registration_number',
            field=models.IntegerField(unique=True, verbose_name='reg_no'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='round_group1_qualified',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='g1'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='round_group2_qualified',
            field=models.IntegerField(blank=True, null=True, verbose_name='g2'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='round_group3_qualified',
            field=models.IntegerField(blank=True, null=True, verbose_name='g3'),
        ),
    ]
