# Generated by Django 5.2 on 2025-04-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0012_alter_robot_is_byebot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='author2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='school_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
