# Generated by Django 5.2 on 2025-04-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0014_robot_robot_kit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
