# Generated by Django 5.2 on 2025-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0015_robot_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='number_of_tables',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='round',
            name='round_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
