# Generated by Django 5.2 on 2025-04-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0016_round_number_of_tables_round_round_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
