# Generated by Django 5.2 on 2025-04-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtracker', '0018_alter_match_result_robot1_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='schedule_table',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
